### ISSUE TITLE
getCurrrentConnectionType for Windows may not be accurate for some locked down corporate networks

### ISSUE THREAD

**Issue by pjc2007** [apache/cordova-plugin-network-information#100]
# Bug Report

## Problem
I am not sure if you want to consider this a bug, as perhaps my use case is a bit out of the ordinary, but thought would just bring to light.

For now, I have called the Windows API directly to get around this.

Running on a more "locked down" corporate network, `getCurrrentConnectionType()`  would return NONE for windows when trying to get to a local server (ie server on the same network)

Seems only to be Windows, the problem occurs, Have not tried iOS yet, but Android appear ok.

### What is expected to happen?
Would like this to report the connected network

### What does actually happen?
`getCurrrentConnectionType`   returns NONE

## Information
In my case, the call to `profile.getNetworkConnectivityLevel();` was returning `NetworkConnectivityLevel.LocalAccess`, but if I did a http call anyway, it worked fine

### Environment, Platform, Device
A locked down corporate network that probably did not allow outside network access, but in this case the server is located on the local network

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
