### ISSUE TITLE
OnConnect event fired when USB device connected on Android. Using latest version.

### ISSUE THREAD

**Issue by PabloGO1108** [apache/cordova-plugin-network-information#101]
# Bug Report
OnConnect event fired when USB device connected on Android. It's on Ionic 5 app. I have tested on two real devices.

When downgrading to 2.0.1 everything works fine. Is there another fix?

### Version information
Ionic CLI                     : 5.4.15 (/usr/lib/node_modules/ionic)
Ionic Framework               : @ionic/angular 4.11.5
@angular-devkit/build-angular : 0.801.3
@angular-devkit/schematics    : 8.1.3
@angular/cli                  : 8.1.3
@ionic/angular-toolkit        : 2.1.1
Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0
cordova-plugin-network-information: 2.0.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
This may be fixed by https://github.com/apache/cordova-plugin-network-information/pull/111

Are you able to test?

**Comment by breautek** [comment]
Tested and confirmed the bug on latest version. Tested PR https://github.com/apache/cordova-plugin-network-information/pull/114 and it also solves this bug.
