### ISSUE TITLE
Need 1.2.2-dev version

### ISSUE THREAD

**Issue by kamruzzaman2** [apache/cordova-plugin-network-information#105]
Need 1.2.2-dev version

I used it in my cordova application.
But now i didn't find this version. When i used older or latest version of this plugin my application is not working. Eagerly need this version.

**Comment by timbru31** [comment]
**very very** recommend way of installing the last version of 1.2.2-dev:
--you should really upgrade, there is no support for this version anymore!--

`cordova plugin add https://github.com/apache/cordova-plugin-network-information.git#a697d3a578e280983b518e3f72ac333fb86f2bbf`
