### ISSUE TITLE
IOS 13.4 not working offline

### ISSUE THREAD

**Issue by Seunghan-Park** [apache/cordova-plugin-network-information#108]
# Bug Report

### What is expected to happen?

I am currently conducting tests on iOS 13.4.
I turned off the Lte and turned off the Wi-Fi connection.
However, plug-in run online functions.
The current network status is also displayed as Wi-Fi.

How can i do?

### What does actually happen?

The current network status is also displayed as Wi-Fi.

## Information
It should be displayed offline when there is no Wi-Fi connection in iOS 13.4.

### Environment, Platform, Device

IOS 13.4 (IPhone X)

### Version information

Cordova-ios => 5.11
Plugin => 2.0.2

## Checklist

- [ O ] I searched for existing GitHub issues
- [ O ] I updated all Cordova tooling to most recent version
- [ O ] I included all the necessary information above

**Comment by Seunghan-Park** [comment]
Sorry I connected VPN.

**Comment by bazuka5801** [comment]
@theseung How do you solve this problem with vpn?
