### ISSUE TITLE
core.js:6014 ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pradipkachhadiya** [apache/cordova-plugin-network-information#109]
![image](https://user-images.githubusercontent.com/16619252/81040159-5510f700-8ec8-11ea-8648-39a8df772557.png)

ionic 4,5 triggering this issue.

> "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^9.0.1",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/app-version": "^5.22.0",
    "@ionic-native/camera": "^5.21.5",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/file": "^5.21.5",
    "@ionic-native/file-transfer": "^5.21.6",
    "@ionic-native/image-picker": "^5.21.5",
    "@ionic-native/keyboard": "^5.21.5",
    "@ionic-native/network": "^5.23.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.2.0",
    "@types/hammerjs": "^2.0.36",
    "cordova-android": "^7.1.4",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-sqlite-storage": "^4.0.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "moment": "^2.24.0",
    "ngx-material-timepicker": "^5.1.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

**Comment by pradipkachhadiya** [comment]
https://github.com/apache/cordova-plugin-network-information/issues/71

tried all thing from above ticket but not working

**Comment by breautek** [comment]
The error/infinite recursion appears to be in `setupSubscription` in the file `fromEvent.js`, which is not part of the Cordova codebase. For that reason, I will close this ticket. I assume this is part of Ionic's codebase, but I'm not familiar with ionic so not 100% sure.

I'd suggest investigating who owns that file, and then opening up an issue in the appropriate repository.

If you think you've found a bug within cordova's codebase, then please do open a new issue and fill out the issue form completely.
