### ISSUE TITLE
5G detect support

### ISSUE THREAD

**Issue by fiflKTH** [apache/cordova-plugin-network-information#145]
# Feature Request

## Motivation Behind Feature
Recently, a lot of device support 5G celluar. and some people need 5g support in this lib. 

## Feature Description
if connected network celluar is 5G, `navigator.connection.type` return '5G'.

## Alternatives or Workarounds
nope.

I already know, this feature discuss in [issues](https://github.com/apache/cordova-plugin-network-information/pull/130). 
Is there any plan update this lib version what 5g detect feature attached?

**Comment by breautek** [comment]
The main issue with https://github.com/apache/cordova-plugin-network-information/pull/130 is that the PR is changing things that shouldn't be changed and the PR author hasn't taken the time to make those corrections unfortunately. As a result, the PR cannot be merged in it's current state.

Another PR can be created to add 5G detection support to supersede that existing PR.

Closing as duplicate: https://github.com/apache/cordova-plugin-network-information/issues/125

**Comment by breautek** [comment]
Yes it is planned, but "when" I cannot say due to the volunteer nature of Apache projects. It's whenever someone decides to volunteer their time in preparing a pull request.
