### ISSUE TITLE
Network.type is throwing as none after 24 hours of idle

### ISSUE THREAD

**Issue by iamroof** [apache/cordova-plugin-network-information#64]
After 24 hours of idle time, if I try to access network type, plugin throwing as none even though mobile is connected to network.

**Comment by janpio** [comment]
What are the exact steps to reproduce this? Start with `cordova create` and include all necessary steps to build the app - or upload a minimal example to Github and describe the steps to reproduce this. Thank you.

**Comment by candemore1024** [comment]
This plugin worked very well, but this month I've several reports of iOS users with this issue or related.

Environment: Cordova 6.0.0 / iOS 4.1.1 / Plugin version: 1.3.0

My app presents a native dialog with the message "No Internet connection found" and after tap the "OK" button, checks again the connection. Users confirming that they have connection to internet. In the second checking, same issue, the dialog appears again, entering in a loop.  I don't know what is the specific trigger, so I'm not able to reproduce it (yet). 

In my own Iphone, using iOS 11.0, I saw the same issue several times, with the difference that in the second checking, the plugin worked fine. Now I’m testing iOS 12.x.

I asked one user (Iphone 8 plus, iOS 11.4.1), to turn off / on the Iphone and it seems that the problem dissapears. I asked now to activate/deactivate the flight mode, expecting reply.

**Comment by janpio** [comment]
@candemore1024 Is this the same problem as the issue you posted in? Doesn't really sound like it - so please create a new one at https://github.com/apache/cordova-plugin-network-information/issues/new Thanks.

**Comment by candemore1024** [comment]
@janpio, I will create a new one if you want. As I said, I don't know where is the specific trigger of this issue, my code is:

var networkState = navigator.connection.type;
if (networkState == Connection.NONE) {
// alert the user using a dialog (navigator.notification.confirm)
}

This worked perfect in the past, but not now. (networkState == Connection.NONE) when the users are confirming that they have connection to internet (wifi or another type).

Thanks in advance!

**Comment by janpio** [comment]
@iamroof Was your issue also with Android?
@NeoLSN What Android version is running on that device?

What plugin version?
What Cordova CLI and Cordova platform version?
What code are you running?

**Comment by NeoLSN** [comment]
@janpio Android 8.0 / 2.0.1 / 8.0.0 / ionic-angular

**Comment by iamroof** [comment]
@janpio Hi, This issue is only with android. Below is the dev environment

Ionic v3.20.0
Angular v5.2.9
Cordova Android v6.4.0
cordova-plugin-network-information v2.0.1 

Phone Model : Nexus 5x - Android v7, Lenovo K4 Note - Android 6

This issue occurs in almost all tested mobiles. 

isNetworkAvailable(): boolean{
        return (this.network.type === "none") ? false : true;
    }

Above sample snipet is used to check online/offline. 

Reproduce Steps:

Consider application has a button which will consume rest services. Network will be checked before hitting rest services.

1) Open Application
2) Click the button. Network.type gives wifi.
3) Lock your mobile. 
4) Unlock your mobile after 24 hours. You will be in same page of application
5) Click the button again. It gives Network.type as "none" (Checked browser for online connectivity)

This issue will be resolved after killing and reopening the application

**Comment by janpio** [comment]
Nice reproduction steps @iamroof - that should be enough for a developer to debug this.

**Comment by TMesdo** [comment]
Same here and I've also problem in this case : 

1. Connect to WiFi A + 4G (navigator.connection.type : wifi)
2. Move enough to lost WiFi A and phone switch to 4G (navigator.connection.type : 4g)
3. Come back to auto reconnect to WiFi A + 4G (navigator.connection.type : none)

**Comment by regiMario** [comment]
I'm having the same issue. I use an app the next morning and it says no network although i have WIFI.
I haven't been able to reproduce it with say airplane mode on/off either. I'm running 7.1.1 on a Sony Xperia E6883 dual sim model.
Is there any way to give this thing a kick to get it to recheck as a workaround?

**Comment by pjhartin** [comment]
I am also having this issue on iOS, but for me, I just have to simply flick on airplane mode on and off for the network.type to always return NONE

**Comment by janpio** [comment]
Create a new issue please @pjhartin as this seems to be a totally different issue (iOS instead of Android) than this one. Otherwise your problem will get lost.

**Comment by anaaChacon** [comment]
+1

**Comment by anaaChacon** [comment]
What solution is there?

**Comment by shineabel** [comment]
+1

**Comment by shineabel** [comment]
Is there any solution?

**Comment by anaaChacon** [comment]
Hola, tengo un problema con las conexiones a Internet, uso el plugin Network de ionic y el problema que tengo es, cuando el tipo de conexión cambia de wifi a datos y la aplicación está en segundo plano el tipo de conexión que recibe es NONE, tengo que matar la aplicación y volver a iniciarla para que ya todo vaya correctamente, alguien ha experimentado este problema?

**Comment by Siva021** [comment]
Is there any alternative solution for this particular issue?? It seems like important

**Comment by anaaChacon** [comment]
the solution that it poses @PieterVanPoyer has solved the problem for me, but in them there is still no solution, at the moment I am satisfied.

**Comment by BurkusCat** [comment]
Still seeing the issue with @PieterVanPoyer 's forked version. From my experience, it has been happening closer to the 36 hour mark.

**Comment by shineabel** [comment]
> Still seeing the issue with @PieterVanPoyer 's forked version. From my experience, it has been happening closer to the 36 hour mark.

+1

**Comment by paridaJhansi** [comment]
network.connection.type is thorwing unknown in case of ios 14 in case of 4g connection. please help if anyone has faced this issue.
plugin version is 2.0.3

**Comment by PieterVanPoyer** [comment]
> network.connection.type is thorwing unknown in case of ios 14 in case of 4g connection. please help if anyone has faced this issue.
> plugin version is 2.0.3

-> I think you should make a comment on next issue: https://github.com/apache/cordova-plugin-network-information/issues/97 
This issue is closed.
