### ISSUE TITLE
Connection reported as Connection.NONE

### ISSUE THREAD

**Issue by candemore1024** [apache/cordova-plugin-network-information#66]
I've several reports of iOS users with “Connection.NONE” when they are confirming that they have connection to internet (wifi or another type). I don't know where is the specific trigger of this issue, so I'm not able to reproduce it (yet).

My code is:

var networkState = navigator.connection.type;
if (networkState == Connection.NONE) {
// alert the user using a dialog (navigator.notification.confirm)
}

This code worked perfect in the past.

Environment: Cordova 6.0.0 / Cordova iOS 4.1.1 / Plugin version: 1.3.0

If "Connection.NONE", my app presents a native dialog with the message "No Internet connection found" and after tap the "OK" button, checks again the connection. Users confirming that they have connection to internet. After the second checking, same issue, "Connection.NONE" and the dialog appears again, entering in a loop. 

In my own device (Iphone 6 plus), using iOS 11.0, I saw the same issue several times, with the difference that in the second checking, the plugin worked fine.

I asked one user (Iphone 8 plus, iOS 11.4.1), to turn off / on the Iphone and it seems that the problem dissapears, after some time appears again. I asked now to activate/deactivate the flight mode, expecting reply.

**Comment by janpio** [comment]
> Environment: Cordova 6.0.0 / Cordova iOS 4.1.1 / Plugin version: 1.3.0

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

Without current `cordova-ios` and plugin version, it doesn't make sense to debug your problem further.

**Comment by candemore1024** [comment]
Cordova iOS 4.1.1 is working perfect with all the plugins I’ve in my app:

com.adi.plugin.keychainutil
cordova-plugin-console
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-statusbar
cordova-plugin-whitelist
cordova-plugin-x-socialsharing
cordova-sqlite-storage
phonegap-plugin-push

The only issue is the last month with cordova-plugin-network-information 1.3.0. Before, it worked fine with iOS 11.x. I upgraded in the past to Cordova iOS 4.5.4, causing issues with several plugins, that I was not able to solve updating the code or plugin version.

Please let me know more details about the specific reasons or documentation to consider that Cordova iOS 4.1.1 will not work properly with cordova-plugin-network-information

Thanks in advance!

**Comment by janpio** [comment]
I am just not interested in debugging a problem with an app that uses outdated software. 

`cordova-ios` releases were done for a reason - to adapt it to new iOS versions and to fix bugs. So it is very much possible that your problem would be gone with the current release of the platform and your plugin.

Maybe someone else is, good luck.

**Comment by jcesarmobile** [comment]
It's not just the cordova-ios old version, it's also that you are not using latest version of the plugin.
There were some changes made related to returning none, so it might be fixed in latest version.
