### ISSUE TITLE
onDisconnect, onConnect observables never firing

### ISSUE THREAD

**Issue by kevinrodriguez-io** [apache/cordova-plugin-network-information#69]
# Issue:

Observables not firing, 

$ ionic cordova plugin add cordova-plugin-network-information
$ npm install --save @ionic-native/network

### package.json
    "@ionic-native/network": "^4.12.2",
    "cordova-plugin-network-information": "^2.0.1",

### app.module.ts

`import { Network } from "@ionic-native/network";`

```
@NgModule({
  declarations: [ MyApp ],
  imports: [
    BrowserModule,
    ...
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [ IonicApp ],
  entryComponents: [ MyApp ],
  providers: [
    ...
    Network
  ]
})
```

### My code

```

ionViewDidLoad() {
    ...
    this.loadConnectionSubscriptions();
  }

async loadConnectionSubscriptions() {
    console.log(await new Promise(resolve => { setTimeout(() => { resolve(this.network.type); }, 3000); }));
    this.onConnectSubscription = this.network.onConnect().subscribe(
      () => {
        // Wait for connection info to be available
        setTimeout(() => {
          switch (this.network.type) {
            case "2g":
            case "3g":
            case "4g":
            case "cellular":
            case "ethernet":
            case "wifi":
              this.hasConnection = true;
              break;
            case "unknown":
            case "none":
              this.hasConnection = false;
              break;
            default:
              this.hasConnection = true;
              break;
          }
        }, this.WAIT_TIME);
      },
      error => {
        // Unable to fetch connection (?)
        this.alertCtrl
          .create({
            title: "Error fetching connection status",
            subTitle: `${error}`,
            buttons: ["Ok"]
          })
          .present();
      }
    );
    this.onDisconnectSubscription = this.network.onDisconnect().subscribe(
      () => {
        console.log(`${this.network.type}`);
        this.hasConnection = false;
      },
      error => {
        // Unable to fetch connection (?)
        this.alertCtrl
          .create({
            title: "Error fetching connection status",
            subTitle: `${error}`,
            buttons: ["Ok"]
          })
          .present();
      }
    );
  }
```
## Expected behavior:

- hasConnection variable must be set to true when connection is available
- The following line: `console.log(await new Promise(resolve => { setTimeout(() => { resolve(this.network.type); }, 3000); }));` should yield the connection type, but it does yield null on both android and browser.
- onDisconnect should set hasConnection to false

## Current behavior:

- Both observables (onConnect, onDisconnect) never call their subscribers
- - The following line: `console.log(await new Promise(resolve => { setTimeout(() => { resolve(this.network.type); }, 3000); }));` should return "unknown" on browser or the current network type

#### Disclaimer

I do apologize if this is an error related to ionic's implementation of your plugin, but i think it's worth to check.

**Comment by janpio** [comment]
As the plugin doesn't contain any observables at all, this will be impossible to solve on this level.

If I were you, I would create a new Cordova app with `cordova create` and implement the plugin directly, then see if works as expected with the "plain" code this plugin offers. If this is the case, the problem is in the Ionic Native implementation. If not, you can come back here and open a new issue which Cordova can actually help with. Thanks.

(Thanks for the well written issue though. You might want to include `ionic info` output next time so all relevant versions are covered as well.)

**Comment by utopiafx** [comment]
Confirmed , it doesn't being triggered for me anymore:

this is my settings:
`
local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 7.0.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v9.3.0
    npm        : 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : ~/Library/Android/sdk

Misc:

    backend : pro
`

My code are similar
