### ISSUE TITLE
ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RHinderiks** [apache/cordova-plugin-network-information#71]
Hello,

I'm trying to use this plugin in ionic 4 beta.7. It worked fine in ionic 3 but now causes: 

ERROR RangeError: Maximum call stack size exceeded
    at setupSubscription (fromEvent.js:27)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46) in core.js

Commenting out the following lines removes the error:

`this.network.onDisconnect().subscribe(() => { });`

**Comment by RHinderiks** [comment]
ionic info:

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/Users/robinhinderiks/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/Users/robinhinderiks/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.0.0
   NodeJS            : v8.11.4 (/Users/robinhinderiks/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

**Comment by janpio** [comment]
You have opened an issue at the Cordova plugin. If the plugin worked with Ionic 3, it can't suddenly be broken with Ionic 4. Ionic 4 or the Ionic Native wrapper you are using of course can be broken. Please open an issue at their repositories.

**Comment by janpio** [comment]
(That being said, you are using an out of date Cordova CLI, which might be causing all kinds of problems.  You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update)

**Comment by RHinderiks** [comment]
Will do, thanks

**Comment by RHinderiks** [comment]
@janpio Weird things are happening. Trying to update cordova its just stuck on 7.1.0 Tried the following:

- sudo npm update -g cordova
- cordova -v returns 7.1.0
=
- sudo npm uninstall -g cordova
- sudo npm install -g cordova
+ cordova@8.0.0
- cordova -v still returns 7.1.0

Am i missing something. I also tried deleting node_modules and installing fresh but no luck

**Comment by janpio** [comment]
Local `cordova` install maybe?

Otherwise use the big hammer: Uninstall your node, install nvm and install a new node via nvm.

**Comment by pradipkachhadiya** [comment]
@janpio same thing working on ionic 5 but not in ionic v4
