### ISSUE TITLE
Differentiate between connections?

### ISSUE THREAD

**Issue by dhruvdp** [apache/cordova-plugin-network-information#73]
While using navigator['connection].type while connected to Verizon cellular 4g and local wifi, the plugin returns '4g' as the network type even though the device's preferred connection is wifi(which is the case for most devices). How can I differentiate/solve this? Thank you.

**Comment by timbru31** [comment]
Hi @dhruvdp,

could you please provide some more context? On which platform do you experience this issue? At least for iOS you can only be connected to either WiFI or LTE/4G and WiFi has a higher priority (AFAIK).

**Comment by timbru31** [comment]
Closing due to lack of feedback and missing information.
