### ISSUE TITLE
Error: Connection is not defined

### ISSUE THREAD

**Issue by hriziya** [apache/cordova-plugin-network-information#80]
I have installed the plugin correctly and it was working earlier. after few months, today I am trying to run the application on my phone and hitting with this error. 

I do not see it reported by others yet so not sure if this is specific to my phone? 
I am on Android 8.1.0, ColorOS Version v5.1

`states[Connection.UNKNOWN] = 'Unknown connection';`

```message: "Connection is not defined"
stack: "ReferenceError: Connection is not defined
at eval (eval at checkConnection (file:///android_asset/www/js/index.js:560:5), <anonymous>:1:1)
at checkConnection (file:///android_asset/www/js/index.js:560:5)
at doLogin

**Comment by janpio** [comment]
What is your actual code? Or is it just the one line you posted?

**Comment by hriziya** [comment]
My code is the function to `checkConnection()`
```
function checkConnection() {
    if (navigator
       && navigator.connection
       && navigator.connection.type) {

        var networkState = navigator.connection.type;

        if(typeof(Connection) != 'undefined')
        {
            var states = {};
            states[Connection.UNKNOWN] = 'Unknown connection';
            states[Connection.ETHERNET] = 'Ethernet connection';
            states[Connection.WIFI] = 'WiFi connection';
            states[Connection.CELL_2G] = 'Cell 2G connection';
            states[Connection.CELL_3G] = 'Cell 3G connection';
            states[Connection.CELL_4G] = 'Cell 4G connection';
            states[Connection.CELL] = 'Cell generic connection';
            states[Connection.NONE] = 'No network connection';

            if (networkState == Connection.NONE) {
                showMessage(states[networkState], function () {
                    hideLoading();
                    return false;
                });
            }
            return networkState !== Connection.NONE;
        }
    }

    return true;
}

**Comment by CenaSurya** [comment]
navigate problem

**Comment by CenaSurya** [comment]
navigate is undefined

**Comment by CenaSurya** [comment]
navigate is undefined

**Comment by anaaChacon** [comment]
Hola, tengo un problema con las conexiones a Internet, uso el plugin Network de ionic y el problema que tengo es, cuando el tipo de conexión cambia de wifi a datos y la aplicación está en segundo plano el tipo de conexión que recibe es NONE, tengo que matar la aplicación y volver a iniciarla para que ya todo vaya correctamente, alguien ha experimentado este problema?

**Comment by elbartostrikesagain** [comment]
I also have this problem, only when building on Android. I'm on Android 9, cordova 7.1.0 / phonegap 8.2.2. generated project via the phonegap hello world template.

plugin list shows: `cordova-plugin-network-information 1.3.4`

example code:
```
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() {
        console.log(Connection.NONE)
    },
};
```

Android debug output:
```
01-22 14:51:58.578 29084 29084 D SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 10 : Uncaught ReferenceError: Connection is not defined
01-22 14:51:58.578 29084 29084 I chromium: [INFO:CONSOLE(10)] "Uncaught ReferenceError: Connection is not defined", source: file:///android_asset/www/js/index.js (10)
```

**Comment by gijsbeijer** [comment]
@elbartostrikesagain Worked for me! thanks!

**Comment by Classic-Paterson** [comment]
@elbartostrikesagain `cordova plugin add cordova-plugin-network-information ` was the fix for me, I suspect that it was installed non globally, then another project spun up, and the dependency was lost.

**Comment by breautek** [comment]
Closing due to staleness.

My best advice with the information available is to ensure that you're code is only accessing these properties after the [deviceready](https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready) has fired.

If the issue persists, don't hesitate to open a new issue with the issue form filled out.
