### ISSUE TITLE
XCode log: Permission denied for Signal strength query

### ISSUE THREAD

**Issue by reksc** [apache/cordova-plugin-network-information#81]
The plugin basically does what it is supposed to do 👍 **but** I get an error in latest XCode 10 in the console log:

`[NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x283834d00, domain=1, instance=1>`

Is this a known issue that I should ignore?

**Comment by RameshkrishnanV** [comment]
Same issue for me! is there any fix for this?

**Comment by figure-ai** [comment]
Same issue for me! is there any fix for this?

**Comment by jcesarmobile** [comment]
Apple SDKs sometimes log things that might sound confusing, but you can just ignore this one.

**Comment by GreenRidingHood** [comment]
that helps me https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-logs

**Comment by rolinger** [comment]
I am not certain this plugin is generating this error.  I am getting this error twice when my app is compiled to a physical iPhone.  I commented out related code and then removed the plugin but my app is still getting the same errors.  I suspect it might be coming from FirebaseX plugin - not certain though.
