### ISSUE TITLE
erro when install plugin and add at providers

### ISSUE THREAD

**Issue by caiquesantosteixeira** [apache/cordova-plugin-network-information#85]
O tipo 'NetworkOriginal' não pode ser atribuído ao tipo 'Provider'.

**Comment by caiquesantosteixeira** [comment]
help me please

**Comment by timbru31** [comment]
Without further information we are sadly unable to help, nor do I speak Portuguese(?), so I can't understand your error message.

`Provider` sound a lot like Angular, you might want to seek support from Ionic if you use any `@ionc-native/` packages.
