### ISSUE TITLE
Determine if a specific connection type is available

### ISSUE THREAD

**Issue by ppetree** [apache/cordova-plugin-network-information#88]
# Feature Request
Determine if a specific connection type is available

## Motivation Behind Feature
I have a dial feature visible only when cellular connections are present.  If the user has both cellular and wifi access, the plugin returns wifi as the connection type but never tells one that cellular is also available.

## Feature Description
bool = Connection.hasConnection(Connection.CELL_4G);

## Alternatives or Workarounds
I got nothing... no idea how to pursue this.  I can't very well popup an alert and tell people to turn off their wifi to access the dial feature.

**Comment by purplecabbage** [comment]
The native apis do not provide a method for this, so this plugin cannot either.
I would think your dial feature should be available all the time, I can make phone calls while I am on wifi ...
