### ISSUE TITLE
Problem with the if function

### ISSUE THREAD

**Issue by Vidpic** [apache/cordova-plugin-network-information#90]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ ] Support Question

The plugin don't work when I try to compare two string with each other.

### Command or Code
document.addEventListener("online", onOnline, false);
  
    function onOnline() {
        var event = new Date();
        var day = event.toLocaleDateString();

        var dTag1 = new Date(2019, 5, 2);
        var sTag1 = dTag1.toLocaleDateString();

        if (day == sTag1) {
            document.getElementById("test").innerhtml = "true";
        } 
           
        }

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by janpio** [comment]
How is your code related to cordova-plugin-network-information?

**Comment by MandelbrotMan** [comment]
Calling New date is going to return the current time that it's called and you'r trying to compare it with a time that you set statically. Everyone gets one.

**Comment by timbru31** [comment]
Closing due to lack of feedback, missing information and a possible solution from MandelbrotMan.
