### ISSUE TITLE
Online event fires every time app resumes from background (iOS and Android)

### ISSUE THREAD

**Issue by EvelinJK** [apache/cordova-plugin-network-information#91]
# Bug Report

## Problem
The online event fires unreliably when an app moves from background to foreground.
This occurs on `iOS AND Android` for us.
It might be related to #82 but it is definitely not resolved with 2.0.2 

### What is expected to happen?
Online event only fires when network connection was lost and is established again.

### What does actually happen?
Online event fires every time the app was in background and comes to foreground again, even though wifi is connected at all times.

## Information
We show a message to the user when he goes offline, and one when he goes online again, so we rely on the event listeners.

Offline works fine, but the online event fires every time the App comes from background to foreground although wifi is connected at all times.

The connection seems to go to `type: none' when the App goes to background, which makes the online event fire when the app comes to foreground again.

We pretty much use the code as in the Cordova documentation, so there's no special implementation that could affect the behavior.

### Environment, Platform, Device
Tested on iOS (12.4) and Android (9 and 6.0.1)

### Version information
React 
cordova 9.0.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by nero120** [comment]
I'm also experiencing this issue, using cordova-plugin-network-information 2.0.2 and cordova-android 8.0.0, on an Android 8 device.

**Comment by ColDrekken** [comment]
Same on my side. On Android it also fired when using Camera from app for some stuff. At the moment im finished with Kamera and close it its like a app resume, which is normaly ok, but i dont see the reason to re-detect network then.

**Comment by paulovargatt** [comment]
I controlled this problem by using a variable

 ```
   disconnectSubscription() {
        this.net.onDisconnect().subscribe(() => {
            this.pageActive = window.location.pathname;
            this.desconect = true;
            return this.nav.navigateForward('app/tabs/network');
        });
    }

    connectSubscription() {
        this.net.onConnect().subscribe(() => {
            if (this.desconect) {
                this.desconect = false;
                return this.nav.navigateRoot(this.pageActive ? this.pageActive : 'app/tabs/home');
            }
        });
    }
```

**Comment by ipehimanshu** [comment]
yes i have same issue for android 6.3.0 so downgrade to old version.

**Comment by brassier** [comment]
I'm seeing the same on at least 2 Android devices (Android 7 and Android 9), using cordova-android 8.1.0.  Downgrading to `2.0.1` of this plugin resolved it, although that's obviously not the desired approach.

**Comment by HansKrywaa** [comment]
same Issue here. Downgrading to 2.0.1 worked for me. Cam someone please fix this? @janpio

**Comment by tryhardest** [comment]
Anyone able to push a fix?

**Comment by HansKrywaa** [comment]
@tryhardest downgrade to 2.0.1

**Comment by tryhardest** [comment]
why downgrade at @HansKrywaa @brassier @ipehimanshu did you try yet @paulovargatt variable above? Will downgrade if needs be yes but I will try with the variable first. Would be nice to get a fix.

**Comment by breautek** [comment]
**For android**, this seems to be a problem with the `Connectivitymanager.getActiveNetworkInfo()` with certain conditions being met on the device, one of which is the app going into the background.

Haven't experimented this myself, but this is what an [stackoverflow answer](https://stackoverflow.com/a/45231746/4685664) suggests.

Good news is that this API is deprecated, and there is supposedly a better way of obtaining connection info, using the [NetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback.html) API.

Bad news is, this API is only available as of API level 21 (Android 5.0) , so it will require a major update and will have to wait until android 4.4 is dropped completely. Android 4.4 will likely be dropped in cordova-android 9, but that is still work-in-progress. If the NetworkCallback API is indeed more consistent and reliable, it won't make it into master until we are ready to prepare a major release, and that release will only happen sometime after cordova-android 9 is release (assuming cordova-android 9 indeed drops support for android 4.4 (API level 19 & 20). PRs are still welcome, even if they need to wait for a major update cycle.

Not experienced enough with iOS to comment on that side of this issue.

**Comment by Shals08** [comment]
Any update on this issue? 
Even am facing the same issue Online/offline event fires every time app resumes from background (iOS and Android)

**Comment by breautek** [comment]
> Any update on this issue?
> Even am facing the same issue Online/offline event fires every time app resumes from background (iOS and Android)

This issue may actually have been fixed by https://github.com/apache/cordova-plugin-network-information/issues/91#issuecomment-660009782 but that hasn't been released yet.

You can test it out on using the nightly version. Do note that nightly versions aren't recommended for production use however.

**Comment by ipehimanshu** [comment]
@breautek 
i confirm that latest master version of this git is solved this issue.
Git solved version : 3.0.0-dev
Thanks

**Comment by breautek** [comment]
Thanks for confirming. This means on the next release the fix will be available for production use. Unfortunately I can't provide any ETA on this will be.

**Comment by brassier** [comment]
@breautek  - can you speak to any release plans for this issue?  Thank you!
