### ISSUE TITLE
bug: Customize phonegap-plugin-barcodescanner add cordova-plugin-network-information get conflict issue

### ISSUE THREAD

**Issue by prakashmp** [apache/cordova-plugin-network-information#92]
Hi Team,
In our project we are using
    

> Customize phonegap-plugin-barcodescanner

and

   

>  ionic cordova plugin add cordova-plugin-network-information

We are getting conflict issue between these two library.Once i Scan the Barcode after that i check for the presence of network at that time app gets crashed.I can't find crash log too!! could you please suggest some solution for this problem.

**Comment by breautek** [comment]
> .I can't find crash log too!! could you please suggest some solution for this problem.

This depends on that platform you're using. On iOS, you'll need to open up xcode to view native logs. On android, you can use `adb logcat` or android studio. I'd recommend android studio since it automatically filters logs to your own application only.

**Comment by PieterVanPoyer** [comment]
@breautek and @prakashmp maybe this issue should be closed? There is no crash log, no extra information, no reproduction repo added to this issue. This issue is not in a decent shape to get working on.

**Comment by breautek** [comment]
Agreed, there haven't been any response from the OP.

If the issue persists, a new issue can be filled out with (hopefully) the issue form filled out.
