### ISSUE TITLE
NFC scan fire onConnect event on Android device

### ISSUE THREAD

**Issue by hschindler** [apache/cordova-plugin-network-information#93]
# Bug Report
NFC scan fire onConnect event
## Problem
When I scan an NFC Tag using ionic recommended nfc plugin "chariotsolutions/phonegap-nfc". Then the onConnect event is fired. And it says that "wifi" ist connected:

Connection: {UNKNOWN: "unknown", ETHERNET: "ethernet", WIFI: "wifi", CELL_2G: "2g", CELL_3G: "3g", …

### What is expected to happen?
The onConnect event should not be fired when you scan an NFC tag.

### What does actually happen?
The onConnect event is fired when you scan an NFC tag.

## Information

It happens in an ionic app.

### Environment, Platform, Device

Tested on Android 5.01 and 9 devices

### Version information

Installed versions:
"@ionic-native/network": "^5.11.0",
"cordova-plugin-network-information": "2.0.2",
@ionic-native/nfc": "^5.3.0",
 "phonegap-nfc": "^1.0.3",
"@ionic/angular": "^4.9.1",
 "cordova-android": "^7.1.4",

## Checklist

- [x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by kyoz** [comment]
Confirmed. I have this problem too :cry:

**Comment by breautek** [comment]
This may be fixed by https://github.com/apache/cordova-plugin-network-information/pull/111

Are you able to test?

**Comment by hschindler** [comment]
I tested the fork https://github.com/PieterVanPoyer/cordova-plugin-network-information.git. (2.0.3-dev)
With that it works.
